server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/user
    username: root
    password: 1234

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

mybatis:
  # mapper 경로 지정
  mapper-locations: query/**/*.xml
  configuration:
    map-underscore-to-camel-case: true